# Generated by Django 2.1.3 on 2022-02-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
